# Generated by Django 4.1.7 on 2023-03-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usericons',
            name='user_icon_path',
            field=models.ImageField(upload_to=''),
        ),
    ]
