# Generated by Django 4.1.7 on 2023-03-30 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatRoom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='time_added',
            field=models.TimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='messages',
            name='group_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatRoom.room'),
        ),
    ]
