# Generated by Django 4.1.7 on 2023-03-30 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0003_rename_messages_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='group_name',
            new_name='group',
        ),
    ]
